export const Permissions = {
  Users: {
    Create: "permission:users.create",
    Update: "permission:users.update",
    Delete: "permission:users.delete",
    View: "permission:users.view",
    Activate: "permission:users.activate",
    Deactivate: "permission:users.deactivate",
    ManageRoles: "permission:users.manageroles",
    GrantPermission: "permission:users.grantpermission",
    RevokePermission: "permission:users.revokepermission",
    ViewAccess: "permission:users.viewaccess",
  },
  Roles: {
    Create: "permission:roles.create",
    Read: "permission:roles.read",
    Update: "permission:roles.update",
    Delete: "permission:roles.delete",
    GrantPermission: "permission:roles.grantpermission",
    RevokePermission: "permission:roles.revokepermission",
    ViewAccess: "permission:roles.viewaccess",
    Assign: "permission:roles.assign",
  },
  Locations: {
    Create: "permission:locations.create",
    Read: "permission:locations.read",
    Update: "permission:locations.update",
    Delete: "permission:locations.delete",
    Move: "permission:locations.move",
  },
  Trades: {
    Create: "permission:trades.create",
    Read: "permission:trades.read",
    Update: "permission:trades.update",
    Delete: "permission:trades.delete",
  },
  Vendors: {
    View: "permission:vendors.view",
    Create: "permission:vendors.create",
    Edit: "permission:vendors.edit",
    Delete: "permission:vendors.delete",
  },
  Categories: {
    View: "permission:categories.view",
    Create: "permission:categories.create",
    Edit: "permission:categories.edit",
    Delete: "permission:categories.delete",
  },
  MaterialStores: {
    View: "permission:materialstores.view",
    Create: "permission:materialstores.create",
    Edit: "permission:materialstores.edit",
    Delete: "permission:materialstores.delete",
  },
  TaskDefinitions: {
    View: "permission:taskdefinitions.view",
    Create: "permission:taskdefinitions.create",
    Edit: "permission:taskdefinitions.edit",
    Delete: "permission:taskdefinitions.delete",
  },
  MaintenancePlans: {
    View: "permission:maintenanceplans.view",
    Create: "permission:maintenanceplans.create",
    Update: "permission:maintenanceplans.update",
    Activate: "permission:maintenanceplans.activate",
    Deactivate: "permission:maintenanceplans.deactivate",
    Delete: "permission:maintenanceplans.delete",
  },
  MaterialItems: {
    View: "permission:materialitems.view",
    Create: "permission:materialitems.create",
    Update: "permission:materialitems.update",
    Delete: "permission:materialitems.delete",
    ManageStock: "permission:materialitems.managestock",
    TransferStock: "permission:materialitems.transferstock",
  },
  PurchaseOrders: {
    Create: "permission:purchaseorders.create",
    Read: "permission:purchaseorders.read",
    Update: "permission:purchaseorders.update",
    Receive: "permission:purchaseorders.receive",
    Cancel: "permission:purchaseorders.cancel",
  },
  StockTransactions: {
    Read: "permission:stocktransactions.read",
  },
  Equipment: {
    View: "permission:equipment.view",
    Create: "permission:equipment.create",
    Edit: "permission:equipment.edit",
    Delete: "permission:equipment.delete",
    ChangeStatus: "permission:equipment.changestatus",
  },
  WorkOrders: {
    View: "permission:workorders.view",
    Create: "permission:workorders.create",
    Update: "permission:workorders.update",
    ManageTasks: "permission:workorders.managetasks",
    Schedule: "permission:workorders.schedule",
    Start: "permission:workorders.start",
    Terminate: "permission:workorders.terminate",
    Cancel: "permission:workorders.cancel",
    IssueMaterials: "permission:workorders.issuematerials",
    Assign: "permission:workorders.assign",
    ReturnMaterials: "permission:workorders.returnmaterials",
  },
} as const;

export type PermissionString =
  (typeof Permissions)[keyof typeof Permissions][keyof (typeof Permissions)[keyof typeof Permissions]];
